/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Plan = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'dateText' : IDL.Text,
});
export const Poll = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'question' : IDL.Text,
  'votes' : IDL.Vec(IDL.Nat),
  'timestamp' : IDL.Int,
  'options' : IDL.Vec(IDL.Text),
});
export const UserProfileWithRole = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'role' : IDL.Text,
});
export const WorkPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
});
export const Candidate = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'voteCount' : IDL.Nat,
  'name' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
});
export const LeaderboardEntry = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'rank' : IDL.Nat,
  'totalScore' : IDL.Nat,
});
export const NewsPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isAnnouncement' : IDL.Bool,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const NewsRequest = IDL.Record({
  'id' : IDL.Nat,
  'requester' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'requesterName' : IDL.Text,
});
export const GameChallenge = IDL.Record({
  'id' : IDL.Nat,
  'challengerUsername' : IDL.Text,
  'challengedUsername' : IDL.Text,
  'timestamp' : IDL.Int,
  'gameName' : IDL.Text,
});
export const WorkResponse = IDL.Record({
  'id' : IDL.Nat,
  'responder' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'postId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCandidate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([IDL.Nat], [], []),
  'createNewsPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'createPlan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPoll' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'createWorkPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteLeaderboardEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteNewsPost' : IDL.Func([IDL.Nat], [], []),
  'deletePlan' : IDL.Func([IDL.Nat], [], []),
  'dismissChallenge' : IDL.Func([IDL.Nat], [], []),
  'dismissNewsRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getAllPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(UserProfileWithRole)],
      ['query'],
    ),
  'getAllWorkPosts' : IDL.Func([], [IDL.Vec(WorkPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getElectionResults' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getElectionStatus' : IDL.Func(
      [],
      [IDL.Record({ 'totalVotes' : IDL.Nat, 'isOpen' : IDL.Bool })],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getNewsRequests' : IDL.Func([], [IDL.Vec(NewsRequest)], ['query']),
  'getPendingChallenges' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GameChallenge)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoterList' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getWorkPostResponses' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkResponse)],
      ['query'],
    ),
  'hasVoted' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCandidate' : IDL.Func([IDL.Nat], [], []),
  'respondToWorkPost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGameChallenge' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'setElectionOpen' : IDL.Func([IDL.Bool], [], []),
  'setLeaderboardEntry' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'submitNewsRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCandidate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateNewsPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'voteInPoll' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Plan = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'dateText' : IDL.Text,
  });
  const Poll = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'question' : IDL.Text,
    'votes' : IDL.Vec(IDL.Nat),
    'timestamp' : IDL.Int,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserProfileWithRole = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'role' : IDL.Text,
  });
  const WorkPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
  });
  const Candidate = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'voteCount' : IDL.Nat,
    'name' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
  });
  const LeaderboardEntry = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'rank' : IDL.Nat,
    'totalScore' : IDL.Nat,
  });
  const NewsPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isAnnouncement' : IDL.Bool,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const NewsRequest = IDL.Record({
    'id' : IDL.Nat,
    'requester' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'requesterName' : IDL.Text,
  });
  const GameChallenge = IDL.Record({
    'id' : IDL.Nat,
    'challengerUsername' : IDL.Text,
    'challengedUsername' : IDL.Text,
    'timestamp' : IDL.Int,
    'gameName' : IDL.Text,
  });
  const WorkResponse = IDL.Record({
    'id' : IDL.Nat,
    'responder' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'postId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCandidate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([IDL.Nat], [], []),
    'createNewsPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'createPlan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPoll' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'createWorkPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteLeaderboardEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteNewsPost' : IDL.Func([IDL.Nat], [], []),
    'deletePlan' : IDL.Func([IDL.Nat], [], []),
    'dismissChallenge' : IDL.Func([IDL.Nat], [], []),
    'dismissNewsRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getAllPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(UserProfileWithRole)],
        ['query'],
      ),
    'getAllWorkPosts' : IDL.Func([], [IDL.Vec(WorkPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getElectionResults' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getElectionStatus' : IDL.Func(
        [],
        [IDL.Record({ 'totalVotes' : IDL.Nat, 'isOpen' : IDL.Bool })],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getNewsRequests' : IDL.Func([], [IDL.Vec(NewsRequest)], ['query']),
    'getPendingChallenges' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GameChallenge)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoterList' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
    'getWorkPostResponses' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkResponse)],
        ['query'],
      ),
    'hasVoted' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCandidate' : IDL.Func([IDL.Nat], [], []),
    'respondToWorkPost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGameChallenge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'setElectionOpen' : IDL.Func([IDL.Bool], [], []),
    'setLeaderboardEntry' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'submitNewsRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCandidate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateNewsPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'voteInPoll' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };