/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : bigint,
  'bio' : string,
  'voteCount' : bigint,
  'name' : string,
  'photo' : [] | [string],
}
export interface GameChallenge {
  'id' : bigint,
  'challengerUsername' : string,
  'challengedUsername' : string,
  'timestamp' : bigint,
  'gameName' : string,
}
export interface LeaderboardEntry {
  'id' : bigint,
  'studentName' : string,
  'scores' : Array<[string, bigint]>,
  'rank' : bigint,
  'totalScore' : bigint,
}
export interface NewsPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isAnnouncement' : boolean,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface NewsRequest {
  'id' : bigint,
  'requester' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'requesterName' : string,
}
export interface Plan {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'dateText' : string,
}
export interface Poll {
  'id' : bigint,
  'creator' : Principal,
  'question' : string,
  'votes' : Array<bigint>,
  'timestamp' : bigint,
  'options' : Array<string>,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'userId' : Principal,
}
export interface UserProfileWithRole {
  'username' : string,
  'displayName' : string,
  'userId' : Principal,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkPost {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface WorkResponse {
  'id' : bigint,
  'responder' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'postId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCandidate' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[bigint], undefined>,
  'createNewsPost' : ActorMethod<[string, string, boolean], bigint>,
  'createPlan' : ActorMethod<[string, string, string], bigint>,
  'createPoll' : ActorMethod<[string, Array<string>], bigint>,
  'createWorkPost' : ActorMethod<[string, string], bigint>,
  'deleteLeaderboardEntry' : ActorMethod<[bigint], undefined>,
  'deleteNewsPost' : ActorMethod<[bigint], undefined>,
  'deletePlan' : ActorMethod<[bigint], undefined>,
  'dismissChallenge' : ActorMethod<[bigint], undefined>,
  'dismissNewsRequest' : ActorMethod<[bigint], undefined>,
  'getAllPlans' : ActorMethod<[], Array<Plan>>,
  'getAllPolls' : ActorMethod<[], Array<Poll>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileWithRole>>,
  'getAllWorkPosts' : ActorMethod<[], Array<WorkPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getElectionResults' : ActorMethod<[], Array<Candidate>>,
  'getElectionStatus' : ActorMethod<
    [],
    { 'totalVotes' : bigint, 'isOpen' : boolean }
  >,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getNewsPosts' : ActorMethod<[], Array<NewsPost>>,
  'getNewsRequests' : ActorMethod<[], Array<NewsRequest>>,
  'getPendingChallenges' : ActorMethod<[string], Array<GameChallenge>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoterList' : ActorMethod<[bigint], Array<Principal>>,
  'getWorkPostResponses' : ActorMethod<[bigint], Array<WorkResponse>>,
  'hasVoted' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCandidate' : ActorMethod<[bigint], undefined>,
  'respondToWorkPost' : ActorMethod<[bigint, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGameChallenge' : ActorMethod<[string, string, string], bigint>,
  'setElectionOpen' : ActorMethod<[boolean], undefined>,
  'setLeaderboardEntry' : ActorMethod<
    [string, Array<[string, bigint]>],
    undefined
  >,
  'submitNewsRequest' : ActorMethod<[string, string], undefined>,
  'updateCandidate' : ActorMethod<[bigint, string, string], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateNewsPost' : ActorMethod<[bigint, string, string], undefined>,
  'voteInPoll' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];