/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NewsPost {
    id: bigint;
    title: string;
    content: string;
    isAnnouncement: boolean;
    author: Principal;
    timestamp: bigint;
}
export interface Plan {
    id: bigint;
    title: string;
    creator: Principal;
    description: string;
    timestamp: bigint;
    dateText: string;
}
export interface WorkPost {
    id: bigint;
    title: string;
    description: string;
    author: Principal;
    timestamp: bigint;
}
export interface WorkResponse {
    id: bigint;
    responder: Principal;
    message: string;
    timestamp: bigint;
    postId: bigint;
}
export interface NewsRequest {
    id: bigint;
    requester: Principal;
    message: string;
    timestamp: bigint;
    requesterName: string;
}
export interface LeaderboardEntry {
    id: bigint;
    studentName: string;
    scores: Array<[string, bigint]>;
    rank: bigint;
    totalScore: bigint;
}
export interface GameChallenge {
    id: bigint;
    challengerUsername: string;
    challengedUsername: string;
    timestamp: bigint;
    gameName: string;
}
export interface Candidate {
    id: bigint;
    bio: string;
    voteCount: bigint;
    name: string;
    photo?: string;
}
export interface Poll {
    id: bigint;
    creator: Principal;
    question: string;
    votes: Array<bigint>;
    timestamp: bigint;
    options: Array<string>;
}
export interface UserProfile {
    username: string;
    displayName: string;
    userId: Principal;
}
export interface UserProfileWithRole {
    username: string;
    displayName: string;
    userId: Principal;
    role: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCandidate(name: string, bio: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    castVote(candidateId: bigint): Promise<void>;
    createNewsPost(title: string, content: string, isAnnouncement: boolean): Promise<bigint>;
    createPlan(title: string, description: string, dateText: string): Promise<bigint>;
    createPoll(question: string, options: Array<string>): Promise<bigint>;
    createWorkPost(title: string, description: string): Promise<bigint>;
    deleteLeaderboardEntry(id: bigint): Promise<void>;
    deleteNewsPost(id: bigint): Promise<void>;
    deletePlan(id: bigint): Promise<void>;
    dismissChallenge(id: bigint): Promise<void>;
    dismissNewsRequest(id: bigint): Promise<void>;
    getAllPlans(): Promise<Array<Plan>>;
    getAllPolls(): Promise<Array<Poll>>;
    getAllUserProfiles(): Promise<Array<UserProfileWithRole>>;
    getAllWorkPosts(): Promise<Array<WorkPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getElectionResults(): Promise<Array<Candidate>>;
    getElectionStatus(): Promise<{
        totalVotes: bigint;
        isOpen: boolean;
    }>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getNewsPosts(): Promise<Array<NewsPost>>;
    getNewsRequests(): Promise<Array<NewsRequest>>;
    getPendingChallenges(username: string): Promise<Array<GameChallenge>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    getVoterList(candidateId: bigint): Promise<Array<Principal>>;
    getWorkPostResponses(postId: bigint): Promise<Array<WorkResponse>>;
    hasVoted(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    removeCandidate(id: bigint): Promise<void>;
    respondToWorkPost(postId: bigint, message: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendGameChallenge(challengerUsername: string, challengedUsername: string, gameName: string): Promise<bigint>;
    setElectionOpen(open: boolean): Promise<void>;
    setLeaderboardEntry(studentName: string, scores: Array<[string, bigint]>): Promise<void>;
    submitNewsRequest(requesterName: string, message: string): Promise<void>;
    updateCandidate(id: bigint, name: string, bio: string): Promise<void>;
    updateDisplayName(name: string): Promise<void>;
    updateNewsPost(id: bigint, title: string, content: string): Promise<void>;
    voteInPoll(pollId: bigint, optionIndex: bigint): Promise<void>;
}
import type { Candidate as _Candidate, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCandidate(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCandidate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCandidate(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async castVote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0);
            return result;
        }
    }
    async createNewsPost(arg0: string, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewsPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewsPost(arg0, arg1, arg2);
            return result;
        }
    }
    async createPlan(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlan(arg0, arg1, arg2);
            return result;
        }
    }
    async createPoll(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1);
            return result;
        }
    }
    async createWorkPost(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkPost(arg0, arg1);
            return result;
        }
    }
    async deleteLeaderboardEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeaderboardEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeaderboardEntry(arg0);
            return result;
        }
    }
    async deleteNewsPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsPost(arg0);
            return result;
        }
    }
    async deletePlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlan(arg0);
            return result;
        }
    }
    async dismissChallenge(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissChallenge(arg0);
            return result;
        }
    }
    async dismissNewsRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissNewsRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissNewsRequest(arg0);
            return result;
        }
    }
    async getAllPlans(): Promise<Array<Plan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans();
            return result;
        }
    }
    async getAllPolls(): Promise<Array<Poll>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPolls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPolls();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfileWithRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getAllWorkPosts(): Promise<Array<WorkPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkPosts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getElectionResults(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getElectionResults();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElectionResults();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getElectionStatus(): Promise<{
        totalVotes: bigint;
        isOpen: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getElectionStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElectionStatus();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getNewsPosts(): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPosts();
            return result;
        }
    }
    async getNewsRequests(): Promise<Array<NewsRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsRequests();
            return result;
        }
    }
    async getPendingChallenges(arg0: string): Promise<Array<GameChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingChallenges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingChallenges(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoterList(arg0: bigint): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoterList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoterList(arg0);
            return result;
        }
    }
    async getWorkPostResponses(arg0: bigint): Promise<Array<WorkResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkPostResponses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkPostResponses(arg0);
            return result;
        }
    }
    async hasVoted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVoted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVoted();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeCandidate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCandidate(arg0);
            return result;
        }
    }
    async respondToWorkPost(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToWorkPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToWorkPost(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendGameChallenge(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGameChallenge(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGameChallenge(arg0, arg1, arg2);
            return result;
        }
    }
    async setElectionOpen(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setElectionOpen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setElectionOpen(arg0);
            return result;
        }
    }
    async setLeaderboardEntry(arg0: string, arg1: Array<[string, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLeaderboardEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLeaderboardEntry(arg0, arg1);
            return result;
        }
    }
    async submitNewsRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitNewsRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitNewsRequest(arg0, arg1);
            return result;
        }
    }
    async updateCandidate(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updateNewsPost(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsPost(arg0, arg1, arg2);
            return result;
        }
    }
    async voteInPoll(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteInPoll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteInPoll(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Candidate_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Candidate {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    voteCount: bigint;
    name: string;
    photo: [] | [string];
}): {
    id: bigint;
    bio: string;
    voteCount: bigint;
    name: string;
    photo?: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        voteCount: value.voteCount,
        name: value.name,
        photo: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Array<Candidate> {
    return value.map((x)=>from_candid_Candidate_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
